### ISSUE TITLE
Mapping of mod position

### ISSUE THREAD

**Issue by ArtiVlasov** [computational-ms/unimod-mapper#13]
Is there a reason why the position arg is not mapped via the unimod_mapper to have the "unimod-style" instead of extracting the pos from the "ursgal_style" mod string?

```
mod_dict = {
                "_id": ursgal_index,
                "aa": aa,
                "mass": mass,
                "pos": pos,
                "name": name,
                "composition": composition,
                "org": mod,
                "id": unimod_id,
                "unimod": unimod,
            }
```
where `pos = mod_params[2].strip()`.

Thus, in ursgal_style we call it "Prot-N-term", while in unimod it called "Protein N-term". I see the space, but don't see where it breaks the code yet ^^ 

I am currently working on extracting the neutral info info for a given mod from the unimod.xml so I would simply add the position extraction as well.

**Comment by StSchulze** [comment]
Hmm, I'm not sure why it would need to be mapped?
The mod position is essentially a parameter that is specified by the user. So you could include the translation in uparma, but I'm not sure what the application of mapping it in the unimod_mapper would be.
